- hosts: k8s_workers
  become: true
  remote_user: "{{ user }}"

  vars_files:
    - ansible-vars.yml

  tasks:
    - name: read join command
      debug: msg={{ lookup('file', join_command_location) }}
      register: join_command_local

    - name: show join command
      debug:
        var: join_command_local.msg

    - name: join agents to cluster
      command: "{{ join_command_local.msg }}"
