- hosts: k8s_master
  become: true
  remote_user: "{{ user }}"

  vars_files:
    - ansible-vars.yml

  tasks:

      
    - name: Initialize Kubernetes cluster
      command: "kubeadm init --pod-network-cidr {{ pod_cidr }} --cri-socket unix:///var/run/containerd/containerd.sock"
      args:
        creates: /etc/kubernetes/admin.conf # skip this task if the file already exists
      register: kube_init

    - name: show kube init info
      debug:
        var: kube_init

    - name: Create .kube directory in user home
      file:
        path: "{{ home_dir }}/.kube"
        state: directory
        owner: 1000
        group: 1000
    - name: Configure .kube/config files in user home
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ home_dir }}/.kube/config"
        remote_src: yes
        owner: 1000
        group: 1000

    - name: restart kubelet for config changes
      service:
        name: kubelet
        state: restarted

    - name: apply calico networking
      become: no
      command: kubectl apply -f "https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml"
