- hosts: all # run on the "all" hosts category from ansible-hosts.txt
  # become means be superuser
  become: true
  remote_user: "{{ user }}"

  vars_files:
    - ansible-vars.yml

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: full
        autoremove: yes
        autoclean: yes

    - name: Remove swapfile from /etc/fstab
      mount:
        name: "{{ item }}"
        fstype: swap
        state: absent
      with_items:
        - swap
        - none
    
    - name: Disable swap
      command: swapoff -a
      when: ansible_swaptotal_mb >= 0
    
    - name: reboot to apply swap disable
      reboot:
        reboot_timeout: 180 #allow 3 minutes for reboot to happen

    - name: Add k8s modules to /etc/modules-load.d/k8s.conf
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Load overlay and br_netfilter modules
      command: modprobe {{ item }}
      loop:
        - overlay
        - br_netfilter

    - name: Configure sysctl parameters for k8s
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1

    - name: Apply sysctl params without reboot
      command: sysctl --system
